### ISSUE TITLE
support throwing an error on an unsuccessful getParams, getFormData instead of allowing `.data` being undefined

### ISSUE THREAD

**Issue by gabimor** [kiliman/remix-params-helper#14]
### Describe the bug

Often I use getParams like so. I wish `getParams` just throw an exception on unsuccessful parse instead of me having to check for it everytime

```typescript
const parsedFormData = await getParams(formData, someSchema)

// I wish I didn't have to do this every time
if (!parsedFormData.data) throw new Error("no data")

// do something with
parsedFormData.data.someField
```

### Your Example Website or App

every app

### Steps to Reproduce the Bug or Issue

as listed

### Expected behavior

throwing an exception

### Platform

server

**Comment by kiliman** [comment]
I see. Typically form validation errors are ***expected*** errors, so you should return them to the client so they can fix it. Throwing an Error should be reserved for ***unexpected*** errors. Like errors in your code.

Anyway, given that, you could create a wrapper function.

```ts
async function myGetFormData(request, schema) {
  const result = await getFormData(request, schema)
  if (!result.success) throw new Error("no data")
  return result.data
}
const { someField } = myGetFormData(request, schema)
```
With the wrapper, since you're treating all failed parses as fatal, you can return the data directly. Note how I'm using the `getFormData` helper. It will do the `await request.formData()` for you.

**Comment by kiliman** [comment]
I suppose we could export functions like: `getParamsOrFail()`

**Comment by kiliman** [comment]
We've already used `getParams` for *safe* parsing. Also, I think that's the better default. I'm adding the `*OrFail()` versions. This will be pushed out shortly.
